### PR TITLE
Umitools prepare for rsem

### PR DESCRIPTION
**Pull request by emmarousseau**
## Description

Add prepare-for-rsem UMItools component

## Checklist before requesting a review

- [x] I have performed a self-review of my code

- [x] Conforms to the [Contributing guidelines](https://github.com/viash-hub/base/blob/main/CONTRIBUTING.md)

- [x] Proposed changes are described in the [CHANGELOG.md](https://github.com/viash-hub/base/blob/main/CHANGELOG.md)

- [x] I have tested my code with `viash ns test --parallel -q <name or namespace>`

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [x] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Documentation
  - [ ] Bug fixes

### CODE REVIEW

**Review by tverbeiren — CHANGES_REQUESTED** [review]
Please see code comments.

**Comment by tverbeiren** [comment]
The Python script has an undocumented argument for retrieving the version:

```python
    parser = U.OptionParser(version="%prog version: $Id$", usage=usage, description=globals()["__doc__"])
```

I suggest you use that for version instead of the `pip` dependencies.

**Comment by tverbeiren** [comment]
The name of the component is different in the `CHANGELOG` and the `config.vsh.yaml`, please align.

**Comment by emmarousseau** [comment]
Nirmayi pointed out the you can use the prepare-for-rsem command directly instead of calling the python script, but the version argument for that tools specifically does not work (at least for me), so I included the general umi_tools version.
`umi_tools prepare-for-rsem --version
  # prepare-for-rsem version: $Id$`

**Review by tverbeiren — APPROVED** [review]

**Pull request merged**
